#!/usr/bin/env ruby

require 'git'
require_relative './git_ext'

module GitExt

  include Lib

  def usage
    puts 'git chk #{issue_no} # checkout a branch by a pattern #{issue_no}$'
  end

  def main

    if ARGV.empty?
      usage 
      exit!
    end

    branch_name = ARGV[0]

    g = Git.open(Dir.pwd)

    target_branch = find_from_branch(g, :local, branch_name)
    target_branch = find_from_branch(g, :remote, branch_name) if target_branch.nil?
    error "not found from #{branch_name}" if target_branch.nil?

    exit! if target_branch.name == g.current_branch

    if g.is_local_branch?(target_branch.full)
      target_branch.checkout
    else g.is_remote_branch?(target_branch.full)
      # gでremote branchをcheckoutする方法が分からなかった為、
      # 直接コマンドを実行している
      `git checkout -b #{target_branch.name} #{target_branch.full}`
    end
  end
end

include GitExt
main



