#!/usr/bin/env ruby

require 'git'

def usage
  puts 'git chk #{issue_no} # checkout a branch by a pattern #{issue_no}$'
end

def error(message)
  puts message
  exit!
end

def find_from_branch(g, local_or_remote, branch_name)
  branches = (local_or_remote == :local ? g.branches.local : g.branches.remote)

  # TODO 複数のブランチがヒットした場合
  branches.select { |b| b.name =~ /#{branch_name}$/ }.first
end

def main

  if ARGV.empty?
    usage 
    exit!
  end

  branch_name = ARGV[0]

  g = Git.open(Dir.pwd)
  puts g.current_branch

  target_branch = find_from_branch(g, :local, branch_name)
  target_branch = find_from_branch(g, :remote, branch_name) if target_branch.nil?
  error "not found from #{branch_name}" if target_branch.nil?

  exit! if target_branch.name == g.current_branch

  if g.is_local_branch?(target_branch.full)
    target_branch.checkout
  else g.is_remote_branch?(target_branch.full)
    # gでremote branchをcheckoutする方法が分からなかった為、
    # 直接コマンドを実行している
    `git checkout -b #{target_branch.name} #{target_branch.full}`
  end
end

main



